### ISSUE TITLE
Credits, usage and link back appreciated

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [EwetoyeIbrahim/Flask-Marketplace#13]
Greetings,

Very happy to see that you used [shopyo](https://github.com/shopyo/shopyo) as a base for your project and in particular the e-commerce version of it named [ShopCube](https://github.com/shopyo/shopcube) in inspiration.

We believe referencing our resources such as the [docs](https://shopyo.readthedocs.io/en/latest/) and  using the framework as is or in a proper fashion gives your users better support. You modified the loading systems, effectively rendering your labelling of modular as useless. 

As for legality, you can copy or do whatever you want except getting away with attribution. Here is a copy of our license since sometimes [here](https://github.com/shopyo/shopyo/blob/dev/LICENSE). If you used the framework, fine the license would've been taken care of. But since you copied the work, attribution is appreciated.

In case you suppose that i am mistaken in assuming that you copied Shopyo, then please do consider the following points:

- The modular approach existed before shopyo but pure modules is a Shopyo introduction
- [Factory.py](https://github.com/EwetoyeIbrahim/Flask-Marketplace/blob/master/Flask_Marketplace/factory.py) follows the approach of the generated app.py of Shopyo

And so on. But let's first see what happens.

Cordially yours,

A fellow Flask folk

Edit 1: Legality
Edit 2: Inspiration

**Comment by EwetoyeIbrahim** [comment]
Hello Abdur-rahman,

- Credit claim: I have never set my eyes on any of the two apps you referenced, thus your credit claims are baseless. I will check them out for the first time after closing this issue.
- Modularity: As you can see, it's still a pre-release and things are still being developed at a slow pace due to other tasks at hand and I only devote about 1-2hr/wk development time to this package. With time it will be modular.

For your information:
- The idea of this package stems from [this competition](https://challenge.flutterwave.com/) and the commit submitted for assessment is [this](https://github.com/EwetoyeIbrahim/Flask-Marketplace/tree/80ed6bbc53fd847ec2161bd40f401de37353569d).

Thank you.

**Comment by Abdur-rahmaanJ** [comment]
@EwetoyeIbrahim 

You've responded well, i choose to remove my claims.

As for modular, i suggest you explore the way we build our apps. It might save you some times. 
I might even help you if you wish if 1-2hr/week is what you devote to the app

You've done a great service to the Flask world. I am one of the members of the [Flask Community Workgroup](https://flaskcwg.github.io/). The WG aims among other to support the ecosystem. I believe a project like this is a great piece in the Flask world. It needs more exposure. I'll recontact you soon.
