### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by EwetoyeIbrahim** [EwetoyeIbrahim/Flask-Marketplace#15]
Plugins should be:

1. Placed in a plugin folder at the app root
2. Automatically imported and stitched at startup
2. Able to modify default views
3. Able to add new views

**Comment by Abdur-rahmaanJ** [comment]
@EwetoyeIbrahim Following this with interest, let it mature. I think it will be a good topic for a blog post [in here](https://flaskcwg.github.io/blog/)

**Comment by EwetoyeIbrahim** [comment]
@Abdur-rahmaanJ
I really appreciate the email you sent about making the plugins pip-installable.

Just for a start, the implementation steps in my little reasoning will be:
1. Pip Install Flask-Marketplace
2. Clone plugins into a "plugins" folder at the root of the app.

Why not pip-installable plugins?
* All plugins should be obvious at the plugins directory, instead of automatically searching and installing modules in the python installation directory.
* Uninstalling a plugin will be tedious, as users will need to uninstall the plugin module and may have to look for its dependencies as they cause issues.

Odoo, a standard ERP system, also follows a similar approach for [addons](https://apps.odoo.com/apps).

Thank you.

**Comment by Abdur-rahmaanJ** [comment]
For autoload feature there normally occurs the time when you want to specify what to autoload, just like Django where you must specify what apps to load as there are times when plugins incomplete or no longer compatible etc.  Odoo also has a requirements.txt for apps where you install the dependencies on app install. When you unistall, it uninstall the deps. This does not exclude pip installability.

The idea is more if you want real self-contain plugins like pytest has pip-installable ones. But for a project like this, Django is a better example in terms of the concepts of modules. One thing which also helps a lot is to find out how to simplify front end dev, like having an engine behind instead of recoding everything each time. Odoo has the XML way.

**Comment by EwetoyeIbrahim** [comment]
Thanks for your response.

The little I understand about [Odoo modules](https://apps.odoo.com/apps) are, I also developed [some addons](https://apps.odoo.com/apps/modules/browse?author=Ewetoye):
1. Plugins installation: In Odoo, you place apps in [addon](https://github.com/odoo/odoo/tree/14.0/odoo/addons) folder(s).
    * For a start, we can go the same way.
2. Route modifications: Routes are modified through class inheritance and modifying the needed function(s).
    * For now, we can go the same way.
3. Template modification: Templates are modified by monkey-patching existing ones through XPATH which are only applied on the server, not on the client-side. Their recent framework, [owl.js](https://github.com/odoo/owl), still [doesn't provide a sane way of monkey-patching templates](https://github.com/odoo/owl/issues/312#issuecomment-538946301).
    * Will be glad to get help in this regard while I focus on other features as I am in hurry to implement this project on a live application.

I understand your point that *"...This feature requires more effort on the part of the maintainer of finiding solutions that ease end-users life."* and its going to be addressed one step at a time.

Thank you.
